def chart = api.newChartBuilder()
        .newBarLine()
        .getOptions()
        .setHideLegend(false)
        .setHideTooltips(false)
        .setDisableDrilldown(false)
        .setDisableZoom(false)
        .setShowZAxis(false)
        .setComparisonType(ComparisonType.GROUPED)
        .setZLabel('Other')
        .setBoxplotAxisLabel('Box Plot')
        .back()
        .addSeries()
        .setLabel('Series 1')
        .setDatamart('DM.Standard_Sales_Data')
        .setCurrency('EUR')
        .setHideDataLabels(true)
        .setHideOther(false)
        .setAxisX('ProductId')
        .setAxisY('Quantity').withTotal().back()
        .setType(SeriesType.BAR)
        .withSortByAxisX(SortType.ASCENDING)
        .back()

        .getDictionary()
        .buildFromOpaqueString('[{"sectionIdx":1,"category":"PROJECTION","categoryLabel":"Projection","defaultValue":"Product Id","field":{"name":"ProductId","rank":41,"visibility":1,"source":"DMDS.TXStandardData","sourceField":"ProductId","expression":"ProductId","numeric":false,"system":false,"key":false,"deleted":false,"dimension":true,"auxiliary":false,"deployed":true,"time":false,"calculated":false,"persisted":true,"partitioningKey":false,"queryable":true,"dbColumn":"attribute99","dbTable":"demofx-qa_DM_Standard_Sales_Data","aggregation":false,"type":"TEXT","owningFC":"TXStandardData","messages":{},"label":"Product Id"},"key":"x","keyLabel":"Axis X","sectionLabel":"Series 1","seriesIndex":0},{"sectionIdx":1,"category":"PROJECTION","categoryLabel":"Projection","defaultValue":"∑Quantity","field":{"name":"Quantity","rank":46,"measureType":"EXTENDED","functionalType":"PERUNITBASIS","visibility":1,"source":"DMDS.TXStandardData","sourceField":"Quantity","expression":"Quantity","numeric":true,"system":false,"key":false,"deleted":false,"dimension":false,"auxiliary":false,"deployed":true,"time":false,"calculated":false,"persisted":true,"partitioningKey":false,"queryable":true,"dbColumn":"attribute126","dbTable":"demofx-qa_DM_Standard_Sales_Data","aggregation":false,"type":"QUANTITY","owningFC":"TXStandardData","messages":{},"label":"Quantity"},"key":"y","keyLabel":"Axis Y","sectionLabel":"Series 1","seriesIndex":0}]')
        .back()
        .build()